# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(unique=True, verbose_name='username'),
        ),
    ]
