# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('size_description', models.CharField(default='One size fits all', max_length=100, verbose_name='size description')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='image of sock')),
                ('is_rental', models.BooleanField(default=False, verbose_name='is rental')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sock',
                'verbose_name_plural': 'socks',
            },
        ),
        migrations.CreateModel(
            name='SockMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.PositiveSmallIntegerField(choices=[(1, 'Sock 1'), (2, 'Sock 2')], verbose_name='winner')),
                ('sock1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_sock_1', to='socks.Sock', verbose_name='sock 1')),
                ('sock2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_sock_2', to='socks.Sock', verbose_name='sock 2')),
            ],
            options={
                'verbose_name': 'sock match',
                'verbose_name_plural': 'sock matches',
            },
        ),
    ]
