# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SockPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.PositiveSmallIntegerField(choices=[(1, 'Approve'), (2, 'Disapprove')])),
                ('source_sock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_for_preferences', to='socks.Sock')),
                ('target_sock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_for_preferences', to='socks.Sock')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sockpreference',
            unique_together=set([('source_sock', 'target_sock')]),
        ),
    ]
